language: objective-c
osx_image: xcode7.3
before_install:
- brew update
- brew install tailor
- gem install fir-cli
script:
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/$PROFILE_NAME.mobileprovision.enc
  -d -a -out scripts/profile/$PROFILE_NAME.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a
  -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a
  -out scripts/certs/dist.p12
- "./scripts/add-key.sh"
- ". $bulidTask"
after_success:
- "./scripts/sign-and-upload.sh"
after_script:
- "./scripts/remove-key.sh"
include:
- CavyLifeBand2
env:
  matrix:
  - bulidTask: bulid.sh
  - bulidTask: uitest.sh
  - bulidTask: test.sh
  global:
  - APP_NAME="CavyLifeBand2"
  - 'DEVELOPER_NAME="iPhone Distribution: Hangzhou Cavy Technology Co., Ltd."'
  - PROFILE_NAME="CavyLifeBand2"
  - secure: pLIMzMWmQ/qe1cSB/HjF+ez6VhvGD3NElRPg46zCCmQyaKgWtzSVf+hAE66ifxi0cu02IqzbuEeVhBQwlLe/BIihM28dtjmUcXfjxq9JYIgjGwnl2GFmRRycHedjK1MgSu3/JQ662BsCVV6r4bV5nKBTMH7Lc6rd8aluhvzev2JPYCMidfII8zDIvsz6jAhs9Qi85uzZE52HN9jiFlZOYeLjSKIwjjp4nEdmzuCnTsriktGsoFQFmvTP++1Bhcw6otE0Ahjv2VmP5UaTNEH9/qESnG2f5VjY29R9vtJM7VARidH5ZQ5Rq1OAqYtELBBlXFeleStGfiqhIMIEn/0WiEo0g/sHot/b3kuQXq0xFJ2fqDR5CtRlUM8qdyUvrkCRwzzpweeGWFNT+COahB77FJHCz+f2LMs+0xWlOkBiYIqQ5DN/R1WJxwXfw56sYM/UlZPhNWn9MRynNj/966QGvFXxzPIkbdJtDIQRP8khEjhT1S4iwmZ1OnnbT2znQGb32pv4FVWK/O4M/3Vz6fiddmlRBpcDC++G/bWhaAErxRaRb9whFPlw3uRm0yTsV7/NxLZE87fQ08IsxVJu7DMrY4zTisscMmtC7lLcKAm+X+WWhbCFuuGAtlvxI8Xdp1O4IwbHVOBRHdp9/DCusxjlox24VEGecaPyK1HhFuYziIk=
  - secure: AiRSHA3DwT+R8qpafCa8oykE1fBH63m7YjpjMxfsB8SmDiFUWE5OZWyxcuU2o84ueL/QXtoDp935ODwGNtj4qsOsZ8XTNPUaFhNMG/AfQFAbqg8/yDWZ0zr2wvIS2YcWm8RhitTDwBXpYA32Z5XwayRe8m9N1pxvd2kDa4T6vhEQ9HY6wvVH71fE5gtDlMWfC7GZfAC0h1RO0xHtr+5W9US+MwqI3M6ZV41x1owcX5BHfjoGJ4g1suw9zO5T6WN9moynJG6ryIjq+jN5P7oR1D/1GYBS+o9aYfMSCQoLyNViP7RueXwZqDqDqgaBFXgo0JA+cu9w1La5+dS9OQoazcOY8Jp7hklMkmXp3RPnVwNheKCSK3aNwN7xRFvUbtItONzlCH+We+RHAQn9zncEdt8Mc1yHi2qtK8pUQ+NMT5Hd27Dz5C6D0bgv7Us8Bk1IHqGHM8AB642jAB1iPjxVsEau5E0pHk2vcoX4yt/opM3ENL5nOUZSY3X1hUWpbWHOp9CJa3KZ09HM6OKbaP0QOV40PDTuIsq69GxnxwKKhQ8pkJoaH2Z6KLQ/vfq0xh1WP/fwsRM7ExluQTv02G9NxTmJoTRqjGXyWvFy0Gt6zmP6XJwokMqaPIDkrpd4mTOydGGAQfBkctlqEoNq+KTxkQ4MqqBrIHqGe4NMSQOXAgk=
  - secure: JNwVPizRe8QHMCa5pI4Wm0uy8dEEXem0IxFm+WUDm4+btnl5kI3dQXVWiJsCJq4RlLpCXIwNEAatk6iHruIlgMwr59tQssxXdn9kfwETd8i+Tmc1meVvqpY7AV6+foUy7raDVae+v9ZLf+Cxi5uyrC06R9Xgom4eQA3GMg6kd6zj2kbcKic0BDnVvlT8GWa4+OisRlN1uAdVjxnYrVWs2f0LEqufD2MxqP5IVTeXiWI+LAHhMf1ZlxxjsmehaPpBHdRBzeIi2KJ96k+55vKn+F5nXUO+hxrogwbKq3GZ65QSwhbyvV46i+sdWbA2pAaMIo6J6TMnCz/d+ZcyATm/kN1x9cmNYM8xo6lmr3z3gOKETlaCTt6vb/9TIvTWOq1AvuweLZm8v3xc26uF61PesaO/UF1GHl/M+cCU+P+xWjC1SVXY3boJyC8T2D3RL+4f8mas14H2GjCF9z95A+TqyD+EjbU8nuUS7gteo6r1rVuv1Uc+Psqc3+SxLSCmofMGvTBh4jLbLhNoWg/byTsjJSnDn0QEOUGnwpbQldTCVQuvHj0FL3RlhIDT/XzmB4ExnS24Q5kwhBT23KI5UylXiRfL578wWVENTPms6TgKR3brUryEe6+Y5uEfjAgiLGniq5hw7arWy5933TA24FvpwyuaJQGUtuU8ugAAlJgi5rY=
  - secure: IV6XSUT/xFMAvLHkWUeSVgGcqm1UJFHcpHuUj7tuhxNCWfsPAblv4LZ8+6XVITf+BOM6hbMFDK/Q0jaBzYtRW8CR2BlUqBrpvSvITxqaV+8MQFAIghXLWTP3zE6XBib4sutDy6xsRwZynKxF6U8Tf6v2iyx1/zdlOTKsIbDmhUGpPDXDyouemqJLVbI/Pk5J5dKwIETcYLfHAIo2hCucA0OrhYJQFgLXC2jALbCXg0iAw+5xGuUagSco3NoKGZ9mJtWwJgCzvDvdbaB+eqniSgMeGcm78BlNkeqjiY4MmGXWo3XTVfrq8FtEIvv2U8fsYTdPa/p2Dv7G0IfwiCiocOrn6TvKQdJ47kpPiAAohao8mpDKFoC+tXMi7i9ImOprBtb2p+UDuks1hmrwZLaqyRXLWqh9tyzzCmjKajVSId2rJnmK8L9K0z2tz/0IGP44mV3L0QU/NmDbAVE+46DrxSLbNvOJoJi9m0JdEAHFSeEc/8mf46KgWvh52jHQyCjuSFp3tHAvRmuHmsj8J50+Fv1M6viHM1SoEAckYfQ143ldVckHFiauB6D+IYmYVACzI9vCni3QmSFtAqw5Vc1WHXpe86Vl2cOpdREw0WDN7SXylduWQ8fhfthrbQSwGrvWsusdTn7eqqZBMgOYk2R4EJTcvAxDGME223YAS9MvcSM=
